# Generated by Django 2.2.12 on 2020-05-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_auto_20200509_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'DRIVER ACCEPTED'), ('2', 'DRIVER AT PICKUP LOCATION'), ('3', 'ITEM PICKED && ON GOING'), ('4', 'REACHED DESTINATION'), ('5', 'UNLOADED'), ('6', 'COMPLETED'), ('0', 'BOOKING_WAS_CANCELD')], default='1', max_length=50, verbose_name='Status')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.RunSQL('ALTER TABLE `delivery_delivery` auto_increment = 20000;')
    ]
