# Generated by Django 2.2.12 on 2020-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('status', models.CharField(choices=[('PENDING', 'pending status'), ('PROCESSING', 'processing status'), ('COMPLETED', 'completed status'), ('CANCELD', 'canceld status')], max_length=25)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunSQL('ALTER TABLE `orders_order` auto_increment = 10000;')
    ]