# Generated by Django 2.2.12 on 2020-05-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending status'), ('PROCESSING', 'processing status'), ('COMPLETED', 'completed status'), ('CANCELD', 'canceld status')], default='PENDING', max_length=25),
        ),
    ]
